module IRTS.CodegenElixir(codegenElixir) where

import IRTS.CodegenCommon

import Text.PrettyPrint

codegenElixir :: CodeGenerator
codegenElixir ci = writeFile (outputFile ci) (render source)
  where
    source = vcat sections
    sections =
      [ prelude
      , body
      , epilogue
      ]
    prelude = elixirComment "generated by idris-elixir"
    body = empty
    epilogue = elixirComment "EOF (generated by idris-elixir)"

-- |Emit an Elixir-style comment (line beginning with '#').
-- Doesn't support multiple lines nor line wrapping.
elixirComment :: String -> Doc
elixirComment c = text $ "# " ++ c
